### ISSUE TITLE
Track `numTasks` completed by each account

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-contracts#11]
We should show how many tasks each contributor has created for the currently logged account

- Not exactly sure where this should happen.  
- Probably makes sense to have a user struct in [`DIDToken.sol/Token.sol`](https://github.com/Distense/distense-contracts/blob/1c5a2b686d55a1246a98fd1a17ded2a36d053142/contracts/lib/Token.sol#L14), instead of just tracking balances.
- We could increment this field in the [`issueDID`](https://github.com/Distense/distense-contracts/blob/1c5a2b686d55a1246a98fd1a17ded2a36d053142/contracts/DIDToken.sol#L32) function but would need to check that it is a task being completed that triggers the `issueDID` call and not an investment of ether.

Let's discuss.

**Comment by zepcp** [comment]
What about adding another mapping in Token.sol:
-   mapping (address => uint256) public completedTasks;

Then you could increment the completedTasks on the function approvePullRequest right after issueDID..
What do you think?

**Comment by JohnAllen** [comment]
That won't return the `numTasks` though.  Mappings aren't iterable

**Comment by zepcp** [comment]
True, however I would avoid arrays as much as possible.. If we can keep track of the contributors somehow, we just need a view function to check for each of them that mapping value "completedTasks"..

**Comment by JohnAllen** [comment]
Yeah this should work.  not sure what I was thinking.   Wondering if we should have a `users` mapping with `user` structs

**Comment by JohnAllen** [comment]
that would have potentially their country and repos contributed to track rep across repo, to prevent React people from approving Solidity code :)

**Comment by JohnAllen** [comment]
But we can do it another way
