### ISSUE TITLE
Correctly handle less than 1 whole ether investments in DIDToken

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-contracts#17]
Right now, we [convert wei to ether](https://github.com/Distense/distense-contracts/blob/master/contracts/DIDToken.sol#L125) when someone invests ether for DID.  But we don't track sub-1 ether investments.  So we need to handle any size ether investment, probably sticking to handling wei, until we convert to DIDPerEther.

**Comment by zepcp** [comment]
With your latest commit I think we can close this issue. We require investments of more than 1 DID, and, in that case the code works well.
However, if we want to have decimal cases on the DID token, we should consider using it as ETH, with a representation like WEI to allow several decimal cases..

**Comment by JohnAllen** [comment]
true, if/when DID become super valuable we should allow less than 1 DID investments I suppose.  And we do have 18 decimals already for this purpose -- haven't thought about this yet but it's a good point.
