### ISSUE TITLE
Ensure all math operations in contracts are SafeMath protected

### ISSUE THREAD

**Issue by kfarr** [Distense/distense-contracts#2]

**Comment by zepcp** [comment]
On DIDToken.sol:
- investedAddress[msg.sender] += msg.value;
- investedAggregate += msg.value;

On Distense.sol:
- update = (limitedVotingPower * currentValue) / 10000;
- update = (uint(_voteValue) * currentValue) / 10000;
- update = uint((adjustedVoteValue * int(currentValue)) / 10000);

On Tasks.sol:
- update = (limitedVotingPower * difference) / 10000;
