### ISSUE TITLE
Create ability to withdraw share of ether in DIDToken

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-contracts#6]
Need to have a way of withdrawing one's share of ether over and beyond exchanging DID for ether.

The formula for this should limit the withdrawals by time and percent IMO

**Comment by zepcp** [comment]
I have a question here, we create DID when someone invests (with ETH), or everytime we have a successful/approved PullRequest, right?
Then, how do we ensure that we have enough ETH to give back to all DID holders when they want to withdraw?
Shouldn't we update the DIDPerEther parameter based on the total amount of DID vs the total amount of ETH?

Sorry if it's a dumb question or if it's already answered somewhere but I didn't find it..

**Comment by JohnAllen** [comment]
We won't always have enough ether for everyone to exchange their DID for ether.
